(()=>{'use strict';
const DATA=window.LOCATIONS,ROUTES=window.ROUTES,CITY_NAMES=window.CITY_NAMES,$=id=>document.getElementById(id);
const GROUPS=[['city','Incorporated cities'],['tested','Tested unincorporated'],['supplemental','Additional unincorporated'],['surrounding','Surrounding locations'],['county','Counties'],['highway','Major highways'],['bridge','Bridges'],['road','Major roadways'],['water','Bodies of water']];
let mode='study',target=null,attempts=0,correct=0,boundariesLoaded=false,wrongName=null,routeTemplate=null;const completed=new Set(),review=new Map();
$('poolChecks').innerHTML=GROUPS.map(([g,l],i)=>`<label><input data-group="${g}" type="checkbox" ${i<2?'checked':''}> <span><b>${l}</b><small> — ${items(g).length}</small></span></label>`).join('');
function items(g){return g==='highway'?ROUTES[g].map(x=>({...x,group:g,type:'route'})):DATA.filter(x=>x.group===g).map(x=>({...x,type:'point'}))}
function checked(g){return !!document.querySelector(`input[data-group="${g}"]`)?.checked} function pool(){return GROUPS.flatMap(([g])=>checked(g)?items(g):[])}
const map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:[-121.98,37.94],zoom:9.55,minZoom:7.5,maxZoom:17,attributionControl:true});map.addControl(new maplibregl.NavigationControl(),'top-left');map.addControl(new maplibregl.ScaleControl({maxWidth:120,unit:'imperial'}),'bottom-left');
const query=(base,where,fields)=>base+'/query?where='+encodeURIComponent(where)+'&outFields='+encodeURIComponent(fields)+'&returnGeometry=true&outSR=4326&f=geojson';
const cityWhere="STATE='06' AND BASENAME IN ("+CITY_NAMES.map(n=>"'"+n+"'").join(',')+")", cityURL=query('https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Places_CouSub_ConCity_SubMCD/MapServer/4',cityWhere,'BASENAME,GEOID'), countyURL=query('https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/1',"GEOID='06013'",'BASENAME,GEOID'), regionalURL=query('https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/1',"GEOID IN ('06013','06095','06077','06001','06041','06067')",'BASENAME,GEOID');
function geoBounds(g){let xs=[],ys=[];const w=x=>Array.isArray(x)&&typeof x[0]==='number'?(xs.push(x[0]),ys.push(x[1])):Array.isArray(x)&&x.forEach(w);g.features.forEach(f=>w(f.geometry.coordinates));return xs.length?[[Math.min(...xs),Math.min(...ys)],[Math.max(...xs),Math.max(...ys)]]:null}
async function loadGIS(){try{const rs=await Promise.all([fetch(cityURL),fetch(countyURL),fetch(regionalURL)]),js=await Promise.all(rs.map(r=>r.json()));map.addSource('cities',{type:'geojson',data:js[0]});map.addLayer({id:'city-fill',type:'fill',source:'cities',paint:{'fill-color':'#8fb8d8','fill-opacity':.30}});map.addLayer({id:'city-outline',type:'line',source:'cities',paint:{'line-color':'#394b59','line-width':1.5}});map.addSource('regional-counties',{type:'geojson',data:js[2]});map.addLayer({id:'regional-county-outline',type:'line',source:'regional-counties',layout:{visibility:'none'},paint:{'line-color':'#7058a8','line-width':2}});map.addSource('county',{type:'geojson',data:js[1]});map.addLayer({id:'county-outline',type:'line',source:'county',paint:{'line-color':'#102b42','line-width':3}});const b=geoBounds(js[1]);if(b)map.fitBounds(b,{padding:30,duration:0});boundariesLoaded=true;$('status').textContent='2026 Census city/county boundaries loaded';}catch(e){console.error(e);$('status').textContent='Census boundary service unavailable; map quiz still works'}}
function pointGeo(){return {type:'FeatureCollection',features:pool().filter(x=>x.type==='point').map(p=>({type:'Feature',properties:{name:p.name,group:p.group,status:completed.has(p.name)?'done':wrongName===p.name?'wrong':'open'},geometry:{type:'Point',coordinates:[p.lon,p.lat]}}))}}
function syncPoints(){const src=map.getSource('places');if(src)src.setData(pointGeo());else{map.addSource('places',{type:'geojson',data:pointGeo()});map.addLayer({id:'places',type:'circle',source:'places',paint:{'circle-radius':6.5,'circle-color':['match',['get','status'],'done','#f2b705','wrong','#d73027',['match',['get','group'],'city','#075fe4','tested','#07864c','supplemental','#df5ca8','surrounding','#e67e22','county','#7c4dcc','bridge','#15a7a1','water','#2980b9','road','#d6428b','#777']],'circle-stroke-color':'#fff','circle-stroke-width':1.8}})}}
function syncLabels(){if(map.getLayer('place-labels'))map.removeLayer('place-labels');if(mode==='study'&&$('labels').checked)map.addLayer({id:'place-labels',type:'symbol',source:'places',layout:{'text-field':['get','name'],'text-size':12,'text-offset':[.8,0],'text-anchor':'left'},paint:{'text-color':'#173150','text-halo-color':'rgba(255,255,255,.95)','text-halo-width':1.5}})}
function setBasemapLabels(show){map.getStyle()?.layers?.forEach(l=>{if(l.id!=='place-labels'&&l.type==='symbol'&&l.layout&&('text-field'in l.layout))try{map.setLayoutProperty(l.id,'visibility',show?'visible':'none')}catch{}})}
function findRoadTemplate(){const ls=map.getStyle()?.layers||[];routeTemplate=ls.find(l=>l.type==='line'&&l.source&&l['source-layer']&&/transport|road/i.test(l['source-layer']))||ls.find(l=>l.type==='line'&&l.source&&l['source-layer']);}
function routeFilter(r){const tests=[];(r.keys||[r.name]).forEach(k=>{tests.push(['==',['get','name'],k],['==',['get','ref'],k],['==',['get','name:en'],k])});return ['any',...tests]}
function syncRoutes(){['route-hit','route-open','route-done'].forEach(id=>{if(map.getLayer(id))map.removeLayer(id)});if(!routeTemplate)return;const selected=pool().filter(x=>x.type==='route'), open=selected.filter(x=>!completed.has(x.name)), done=selected.filter(x=>completed.has(x.name));const anyFilter=a=>a.length?['any',...a.map(routeFilter)]:['==',1,0];const base={type:'line',source:routeTemplate.source,'source-layer':routeTemplate['source-layer']};map.addLayer({...base,id:'route-open',filter:anyFilter(open),paint:{'line-color':['case',['==',['get','class'],'motorway'],'#d85b2a','#d6428b'],'line-width':4,'line-opacity':.8}});map.addLayer({...base,id:'route-done',filter:anyFilter(done),paint:{'line-color':'#f2b705','line-width':6,'line-opacity':.95}});map.addLayer({...base,id:'route-hit',filter:anyFilter(selected),paint:{'line-color':'rgba(0,0,0,0.01)','line-width':18}})}
function refresh(){syncPoints();syncLabels();syncRoutes();$('poolCount').textContent=pool().length;updateProgress();renderStudyLists();updateMobileOverlay()}
function isPhone(){return window.matchMedia('(max-width: 600px)').matches}
function updateMobileOverlay(studyItem){const box=$('mobileOverlay');if(!box)return;if(!isPhone()||mode==='list'){box.hidden=true;return}box.hidden=false;if(mode==='quiz'){box.className='mobile-overlay quiz-overlay';box.innerHTML=`<small>QUIZ</small><strong>Find: ${target?target.name:'—'}</strong><span>${pool().filter(p=>completed.has(p.name)).length} of ${pool().length} completed</span>`}else if(studyItem){box.className='mobile-overlay study-overlay';box.innerHTML=`<small>STUDY</small><strong>${studyItem.name}</strong><span>${GROUPS.find(([g])=>g===studyItem.group)?.[1]||studyItem.group}</span>`}else{box.hidden=true}}
function available(){return pool().filter(p=>!completed.has(p.name))} function newQuestion(){const a=available();if(!pool().length){target=null;$('target').textContent='No items enabled';updateMobileOverlay();return}if(!a.length){target=null;$('target').textContent='Round complete!';$('feedback').innerHTML='<span class="good">Review your Study Next list below.</span>';updateMobileOverlay();return}target=a[Math.floor(Math.random()*a.length)];$('target').textContent=target.name;$('feedback').textContent='';updateMobileOverlay()}
function setMode(m){mode=m;$('study').classList.toggle('active',m==='study');$('quiz').classList.toggle('active',m==='quiz');$('listMode').classList.toggle('active',m==='list');$('quizbox').hidden=m!=='quiz';$('mapPanel').hidden=m==='list';$('studyPanel').hidden=m!=='list';$('labels').disabled=m==='quiz';if(m!=='list'){map.resize();setBasemapLabels(m==='study');syncLabels();if(m==='quiz')newQuestion();else updateMobileOverlay()}else updateMobileOverlay();renderStudyLists()}
function markReview(question,wrong){if(!review.has(question))review.set(question,new Set());if(wrong)review.get(question).add(wrong);renderReview()}
function renderReview(){if(!review.size){$('review').textContent='No misses yet.';return}$('review').innerHTML=[...review].map(([q,s])=>`<div><b>${q}</b>${s.size?` — selected: ${[...s].join(', ')}`:' — skipped / review'}</div>`).join('')}
function updateStats(){$('score').textContent=correct+' / '+attempts;$('accuracy').textContent=attempts?Math.round(correct/attempts*100)+'%':'—'}function updateProgress(){$('progress').textContent=pool().filter(p=>completed.has(p.name)).length+' of '+pool().length+' completed'}
function restart(){completed.clear();attempts=0;correct=0;target=null;wrongName=null;updateStats();refresh();if(mode==='quiz')newQuestion()}
function renderStudyLists(){$('studyLists').innerHTML=GROUPS.map(([g,label])=>{const names=items(g).map(x=>x.name).sort((a,b)=>a.localeCompare(b));return `<section><h3>${label} <small>(${names.length})</small></h3><ol>${names.map(n=>`<li>${n}</li>`).join('')}</ol></section>`}).join('')}
function matchRouteFeature(f,r){const p=f.properties||{}, vals=[p.name,p.ref,p['name:en']].filter(Boolean).map(String);return (r.keys||[r.name]).some(k=>vals.includes(k))}
map.on('load',async()=>{await loadGIS();findRoadTemplate();syncPoints();syncLabels();syncRoutes();renderStudyLists();map.on('click','places',e=>{const name=e.features?.[0]?.properties?.name;if(mode==='study'&&isPhone()){const item=pool().find(x=>x.name===name)||DATA.find(x=>x.name===name);if(item)updateMobileOverlay(item);return}handleChoice(name)});if(map.getLayer('route-hit'))map.on('click','route-hit',e=>{if(mode!=='quiz'||!target||target.type!=='route')return;const selected=pool().filter(x=>x.type==='route').find(r=>e.features?.some(f=>matchRouteFeature(f,r)));if(selected)handleChoice(selected.name)});});
function handleChoice(name){if(mode!=='quiz'||!target)return;if(completed.has(name))return;attempts++;if(name===target.name){correct++;completed.add(name);wrongName=null;$('feedback').innerHTML='<span class="good">Correct! '+name+' is complete.</span>';refresh();updateStats();setTimeout(newQuestion,650)}else{markReview(target.name,name);wrongName=name;$('feedback').innerHTML='<span class="bad">That was '+name+'. Try again.</span>';refresh();updateStats();setTimeout(()=>{wrongName=null;syncPoints()},500)}}
$('study').onclick=()=>setMode('study');$('quiz').onclick=()=>setMode('quiz');$('listMode').onclick=()=>setMode('list');$('newq').onclick=newQuestion;$('skip').onclick=()=>{if(target){markReview(target.name,null);newQuestion()}};$('restart').onclick=restart;$('clearReview').onclick=()=>{review.clear();renderReview()};document.querySelectorAll('[data-group]').forEach(x=>x.onchange=()=>{refresh();if(mode==='quiz')newQuestion()});$('labels').onchange=syncLabels;$('cityBounds').onchange=e=>{if(boundariesLoaded)['city-fill','city-outline'].forEach(id=>map.setLayoutProperty(id,'visibility',e.target.checked?'visible':'none'))};$('regionalCountyBounds').onchange=e=>boundariesLoaded&&map.setLayoutProperty('regional-county-outline','visibility',e.target.checked?'visible':'none');$('countyBound').onchange=e=>boundariesLoaded&&map.setLayoutProperty('county-outline','visibility',e.target.checked?'visible':'none');$('opacity').oninput=e=>boundariesLoaded&&map.setPaintProperty('city-fill','fill-opacity',+e.target.value/100);$('reset').onclick=()=>map.flyTo({center:[-121.98,37.94],zoom:9.55});window.addEventListener('resize',()=>{map.resize();updateMobileOverlay();if(map.getLayer('places'))map.setPaintProperty('places','circle-radius',isPhone()?8.5:6.5)});renderReview();renderStudyLists();
})();
