(()=>{'use strict';
const DATA=window.LOCATIONS,CITY_NAMES=window.CITY_NAMES;
const $=id=>document.getElementById(id);
let mode='study',target=null,attempts=0,correct=0,boundariesLoaded=false,wrongName=null;
const completed=new Set();
const map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:[-121.98,37.94],zoom:9.55,minZoom:8.5,maxZoom:17,attributionControl:true});
map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'top-left');map.addControl(new maplibregl.ScaleControl({maxWidth:120,unit:'imperial'}),'bottom-left');
const cityWhere="STATE='06' AND BASENAME IN ("+CITY_NAMES.map(n=>"'"+n.replaceAll("'","''")+"'").join(',')+")";
const query=(base,where,fields)=>base+'/query?where='+encodeURIComponent(where)+'&outFields='+encodeURIComponent(fields)+'&returnGeometry=true&outSR=4326&f=geojson';
const cityURL=query('https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Places_CouSub_ConCity_SubMCD/MapServer/4',cityWhere,'BASENAME,GEOID');
const countyURL=query('https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/1',"GEOID='06013'",'BASENAME,GEOID');
const regionalCountyURL=query('https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/State_County/MapServer/1',"GEOID IN ('06013','06095','06077','06001','06041')",'BASENAME,GEOID');
const enabled=p=>p.group==='city'?$('cityDots').checked:p.group==='tested'?$('testedDots').checked:p.group==='supplemental'?$('suppDots').checked:p.group==='surrounding'?$('surroundDots').checked:$('countyDots').checked;
const pool=()=>DATA.filter(enabled);
const pointGeo=()=>({type:'FeatureCollection',features:pool().map(p=>({type:'Feature',properties:{name:p.name,group:p.group,status:completed.has(p.name)?'done':wrongName===p.name?'wrong':'open'},geometry:{type:'Point',coordinates:[p.lon,p.lat]}}))});
function colorExpr(){return ['match',['get','BASENAME'],'Richmond','#b7a5df','San Pablo','#f2cf7d','El Cerrito','#e9a3c8','Pinole','#f1ad8d','Hercules','#c4a8df','Martinez','#d9a2df','Pleasant Hill','#9fc7ee','Concord','#efa3a3','Clayton','#9cc8ef','Walnut Creek','#e8bd86','Lafayette','#8ed2c2','Orinda','#f2b985','Moraga','#aaa0e6','Danville','#8fc9ea','San Ramon','#8fa9ea','Pittsburg','#f1bd8d','Antioch','#c7a0df','Oakley','#efaaaa','Brentwood','#9cc6e9','#d7c9a7'];}
async function loadGIS(){try{const [c,k,r]=await Promise.all([fetch(cityURL),fetch(countyURL),fetch(regionalCountyURL)]);if(!c.ok||!k.ok||!r.ok)throw new Error('Census GIS HTTP error');const [cities,county,regional]=await Promise.all([c.json(),k.json(),r.json()]);map.addSource('cities',{type:'geojson',data:cities});map.addLayer({id:'city-fill',type:'fill',source:'cities',paint:{'fill-color':colorExpr(),'fill-opacity':.30}});map.addLayer({id:'city-outline',type:'line',source:'cities',paint:{'line-color':'#394b59','line-width':1.5}});map.addSource('regional-counties',{type:'geojson',data:regional});map.addLayer({id:'regional-county-fill',type:'fill',source:'regional-counties',layout:{visibility:'none'},paint:{'fill-color':'#7c63b8','fill-opacity':.06}});map.addLayer({id:'regional-county-outline',type:'line',source:'regional-counties',layout:{visibility:'none'},paint:{'line-color':'#7058a8','line-width':2}});map.addSource('county',{type:'geojson',data:county});map.addLayer({id:'county-outline',type:'line',source:'county',paint:{'line-color':'#102b42','line-width':3}});const b=geoBounds(county);if(b)map.fitBounds(b,{padding:30,duration:0});boundariesLoaded=true;$('status').textContent='Official 2026 Census city + county boundaries loaded';}catch(e){console.error(e);$('status').textContent='Census boundary service unavailable; basemap and quiz dots still work';}}
function geoBounds(g){let xs=[],ys=[];const walk=x=>{if(Array.isArray(x)&&typeof x[0]==='number'){xs.push(x[0]);ys.push(x[1])}else if(Array.isArray(x))x.forEach(walk)};g.features.forEach(f=>walk(f.geometry.coordinates));return xs.length?[[Math.min(...xs),Math.min(...ys)],[Math.max(...xs),Math.max(...ys)]]:null}
function syncPoints(){const src=map.getSource('places');if(src){src.setData(pointGeo());return}map.addSource('places',{type:'geojson',data:pointGeo()});map.addLayer({id:'places',type:'circle',source:'places',paint:{'circle-radius':6.5,'circle-color':['match',['get','status'],'done','#f2b705','wrong','#d73027',['match',['get','group'],'city','#075fe4','tested','#07864c','supplemental','#df5ca8','surrounding','#e67e22','county','#7c4dcc','#777']],'circle-stroke-color':'#fff','circle-stroke-width':1.8}});}
function syncTrainerLabels(){if(map.getLayer('place-labels'))map.removeLayer('place-labels');if(mode==='study'&&$('labels').checked){map.addLayer({id:'place-labels',type:'symbol',source:'places',layout:{'text-field':['get','name'],'text-size':12,'text-offset':[0.8,0],'text-anchor':'left','text-allow-overlap':false},paint:{'text-color':['match',['get','group'],'city','#173150','tested','#175d3c','supplemental','#8c2f66','surrounding','#9a4d00','county','#57348c','#333'],'text-halo-color':'rgba(255,255,255,.92)','text-halo-width':1.5}})}}
function setBasemapLabels(show){const style=map.getStyle();if(!style?.layers)return;style.layers.forEach(l=>{if(l.id==='place-labels')return;if(l.type==='symbol'&&l.layout&&('text-field' in l.layout)){try{map.setLayoutProperty(l.id,'visibility',show?'visible':'none')}catch{}}});}
function refresh(){syncPoints();syncTrainerLabels();$('poolCount').textContent=pool().length;updateProgress()}
function available(){return pool().filter(p=>!completed.has(p.name))}
function newQuestion(){const a=available();if(!pool().length){target=null;$('target').textContent='No locations enabled';$('feedback').textContent='Select at least one study category.';return}if(!a.length){target=null;$('target').textContent='Round complete!';$('feedback').innerHTML='<span class="good">You completed every selected location.</span>';return}let n;do n=a[Math.floor(Math.random()*a.length)];while(a.length>1&&target&&n.name===target.name);target=n;$('target').textContent=n.name;$('feedback').textContent=''}
function setMode(m){mode=m;$('study').classList.toggle('active',m==='study');$('quiz').classList.toggle('active',m==='quiz');$('quizbox').hidden=m!=='quiz';$('labels').disabled=m==='quiz';setBasemapLabels(m==='study');syncTrainerLabels();if(m==='quiz')newQuestion()}
function updateStats(){$('score').textContent=correct+' / '+attempts;$('accuracy').textContent=attempts?Math.round(correct/attempts*100)+'%':'—'}
function updateProgress(){const activeDone=pool().filter(p=>completed.has(p.name)).length;$('progress').textContent=activeDone+' of '+pool().length+' completed'}
function restart(){completed.clear();attempts=0;correct=0;target=null;wrongName=null;updateStats();refresh();if(mode==='quiz')newQuestion()}
map.on('load',async()=>{await loadGIS();syncPoints();syncTrainerLabels();$('poolCount').textContent=pool().length;map.on('click','places',e=>{const p=e.features?.[0]?.properties;if(!p)return;if(mode==='quiz'&&target){if(completed.has(p.name)){$('feedback').textContent=p.name+' is already completed.';return}attempts++;if(p.name===target.name){correct++;completed.add(p.name);wrongName=null;$('feedback').innerHTML='<span class="good">Correct! '+p.name+' is complete.</span>';refresh();updateStats();setTimeout(newQuestion,700)}else{wrongName=p.name;$('feedback').innerHTML='<span class="bad">That was '+p.name+'. Try again.</span>';refresh();updateStats();setTimeout(()=>{if(wrongName===p.name){wrongName=null;syncPoints()}},550)}}else new maplibregl.Popup({closeButton:false}).setLngLat(e.lngLat).setHTML(p.name).addTo(map)});map.on('mouseenter','places',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','places',()=>map.getCanvas().style.cursor='')});
$('study').addEventListener('click',()=>setMode('study'));$('quiz').addEventListener('click',()=>setMode('quiz'));$('newq').addEventListener('click',newQuestion);$('skip').addEventListener('click',()=>{if(target){$('feedback').textContent='Skipped: '+target.name;setTimeout(newQuestion,650)}});$('restart').addEventListener('click',restart);
['labels','cityDots','testedDots','suppDots','surroundDots','countyDots'].forEach(id=>$(id).addEventListener('change',()=>{refresh();if(mode==='quiz')newQuestion()}));
$('cityBounds').addEventListener('change',e=>{if(boundariesLoaded){map.setLayoutProperty('city-fill','visibility',e.target.checked?'visible':'none');map.setLayoutProperty('city-outline','visibility',e.target.checked?'visible':'none')}});$('regionalCountyBounds').addEventListener('change',e=>{if(boundariesLoaded){map.setLayoutProperty('regional-county-fill','visibility',e.target.checked?'visible':'none');map.setLayoutProperty('regional-county-outline','visibility',e.target.checked?'visible':'none')}});$('countyBound').addEventListener('change',e=>{if(boundariesLoaded)map.setLayoutProperty('county-outline','visibility',e.target.checked?'visible':'none')});$('opacity').addEventListener('input',e=>{if(boundariesLoaded)map.setPaintProperty('city-fill','fill-opacity',Number(e.target.value)/100)});$('reset').addEventListener('click',()=>map.flyTo({center:[-121.98,37.94],zoom:9.55}));
})();
